hazelcast:
  timeoutMinutes: 30

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:postgres@localhost/dsl_abac?schema=public
    pool:
      maxSize: 20
    dsl:
      cacheManager: true
      cache:
        Jfolder.expireAfterAccess: 3600000
        Jobject.expireAfterAccess: 600000
  main:
    allow-bean-definition-overriding: true
  security:
    abac.url: r2dbc:postgresql://postgres:postgres@localhost/abac_rules?schema=public
    jwt:
      keystore-path: gateway.p12
      keystore-alias: gateway
      keystore-password: changeit
      expiration: 18000
      iteration: 512
      secret: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTYzMDYxMDI5NX0.m0XU2NvGaAtzptgLfmptj3Fk7S1e1NrBTYTqBAjHoPI8lbRB7z3J52FiLRw-PUZPjQusDt19RszrUQDsZoVXeQ

logging:
  level:
    root: debug
    com.hazelcast.jet.impl: error
    io.r2dbc.postgresql.client: error